Feature/offer logic.ts
mangrovedao/mangrove pull request #137
Opened 2022-01-15 19:56 UTC by jkrivine

Following discussion from issue #111 I implemented the following:
1/ `OfferLogic` is a standalone object that can be obtained from `mgv:Mangrove` (in which case OfferLogic.mgv is passed to the constructor). `OfferLogic` is the class that contains all interaction with a maker contract that do not involve a market (i.e configuration and views).
2/ One can connect `logic:OfferLogic` to a market and obtain a `LiquidityProvider` object that has a `mangrove`, a `market` and a `logic` in its fields. `LiquidityProvider` class implements all function that involves an offer logic and a market.

2022-01-16 15:31 UTC, espendk requested changes
I think this API is clearer 👍

I've made some suggestions, but nothing major.

2022-01-16 15:31 UTC, espendk commented on packages/mangrove.js/src/offerLogic.ts
> +  static async deploy(mgv: Mangrove, contractName: string): Promise<string> {
This signature is very broad (accepts any `contractName`) but the method only works for contracts in the mangrove.js typechain dir. Would be good to clarify this limitation and the intended use in the type and/or comment.

2022-01-16 15:31 UTC, espendk commented on packages/mangrove.js/src/offerLogic.ts
> +        ? ethers.BigNumber.from(2).pow(256).sub(1)
Maybe use `ethers.constants.MaxUint256`

2022-01-16 15:31 UTC, espendk commented on packages/mangrove.js/src/offerLogic.ts
> +      typeof amount === "undefined"
`amount` is declared, so `amount === undefined` is equivalent - and I think it's clearer :-)

2022-01-16 15:31 UTC, espendk commented on packages/mangrove.js/src/offerLogic.ts
> +      | Market
The initial `|` with no left-hand side looks weird to me. What's the point of this?

2022-01-16 15:31 UTC, espendk commented on packages/mangrove.js/src/offerLogic.ts
> +import { LiquidityProvider as LP, Mangrove } from ".";
Why the alias? To me it's confusing as I rarely read imports (they're a necessary annoyance) and thus I wouldn't immediately realize the connection between `LP` and the class `LiquidityProvider`.

2022-01-16 15:31 UTC, espendk commented on packages/mangrove-solidity/scripts/mumbai/prodTests/OfferProxy/OfferProxyActivateMarkets.js
>      const approval = await token.allowance({
Perhaps the `OfferLogic.mangroveAllowance` could be used instead? I think it would be more concise + showcase use of that API.

2022-01-16 15:31 UTC, espendk commented on packages/mangrove.js/test/integration/simplemaker.integration.test.ts
> +      const logic = mgv.offerLogic(mkr_address);
Hoisting `logic` to the suite level (as `lp`) would allow simplifications in the tests: `lp.logic` -> `logic`.
This would also demonstrate, that a `LiquidityProvider` is only required when interacting with a market.

`lp` isn't actually used in most of this suite, so perhaps the suite should be split into two: One for `logic` and one for `lp` ?

2022-01-16 15:31 UTC, espendk commented on packages/mangrove.js/test/integration/simplemaker.integration.test.ts
> +      const lp = await logic.connectMarket({
This isn't used?

2022-01-17 19:44 UTC, jkrivine reviewed
should be OK now

2022-01-17 19:46 UTC, merged