Feature/add logging to mangrove.js
mangrovedao/mangrove pull request #142
Opened 2022-01-17 10:51 UTC by akettal

2022-01-24 13:25 UTC, espendk commented
@akettal I just had a look at the error mesages in cleaning-bot and updategas-bot ("the bots" in the following).

I think the issue is that mangrove.js/src/util/config.ts you set the `NODE_CONFIG_DIR` env variable to a path inside the mangrove.js package. Since the bot tests load mangrove.js before node-config they end up using the `NODE_CONFIG_DIR` set by mangrove.js which is not meaningful.

It makes sense to use the node-config package in mangrove.js, but as it's a library we need to do so in a slightly different manner than in the bots. The documentation describes how it can be done:  https://github.com/lorenwest/node-config/wiki/Sub-Module-Configuration

In addition to fixing the current issue, this approach will also enable us to make it easy for users to configure mangrove.js via configuration files.

2022-01-24 13:46 UTC, espendk commented
I just remembered that there's some more relevant stuff about loading config files inside a library package here: https://github.com/lorenwest/node-config/wiki/Using-Config-Utilities#loadfileconfigsdirectory-options

This is useful if we want to have the configuration defaults for mangrove.js in a file (which I rather like :-))

2022-01-27 20:59 UTC, akettal commented
> I just remembered that there's some more relevant stuff about loading config files inside a library package here: https://github.com/lorenwest/node-config/wiki/Using-Config-Utilities#loadfileconfigsdirectory-options
> 
> This is useful if we want to have the configuration defaults for mangrove.js in a file (which I rather like :-)

Thanks for the advice. mangrove.js is now configurable through a specific namespace, as stated in the README. There also is a default configuration.

2022-01-28 07:49 UTC, espendk requested changes
Looks good :-) I've suggested a few things - let me know if it makes sense.

We should adapt the bots to pass their `logLevel` configuration to mangrove.js - that would be a good test of how easy/elegant this can be done.

2022-01-28 07:49 UTC, espendk commented on packages/commonlib.js/logs/test.log
> +{"level":"warn","message":"erngpiezjrgpijes"}
What's the purpose of this file? I can't see that it's referenced anywhere?

2022-01-28 07:49 UTC, espendk commented on packages/commonlib.js/src/logger.ts
> +  additionnalTransports: Transport[] = []
Minor type (extra 'n'), should be:

```suggestion
  additionalTransports: Transport[] = []
```

2022-01-28 07:49 UTC, espendk commented on packages/commonlib.js/src/logger.ts
> +export const logdataProcessor = (data: Object): string => {
Hmm, this will cause the given data to always be logged as JSON. However, users may want to use other formats in their transports. To allow this, a more flexible approach would be to make a limited depth copy of the `data` object.

Also, a more telling name would be good. Since the purpose is to limit the amount of data logged, perhaps something like `logDataLimiter` ?

2022-01-28 07:49 UTC, espendk commented on packages/mangrove.js/README.md
> +mangrove.js uses `config` package for its configuration.
```suggestion
mangrove.js uses the [node-config](https://github.com/lorenwest/node-config) package for configuration.
```

2022-01-28 22:55 UTC, akettal commented on packages/commonlib.js/logs/test.log
> +{"level":"warn","message":"erngpiezjrgpijes"}
It was mistakenly commited, will remove it.

2022-01-28 22:56 UTC, akettal commented on packages/commonlib.js/src/logger.ts
> +  additionnalTransports: Transport[] = []
Fixed, thanks 👍

2022-01-29 22:53 UTC, akettal commented on packages/commonlib.js/src/logger.ts
> +export const logdataProcessor = (data: Object): string => {
You're right! Fixed.

2022-02-14 15:59 UTC, merged