Add ability to use any fillWants on buy/sell orders.
mangrovedao/mangrove pull request #159
Opened 2022-01-21 16:43 UTC by adhusson

2022-01-21 19:20 UTC, espendk requested changes
nice improvement :-)

2022-01-21 19:20 UTC, espendk commented on packages/mangrove.js/src/types/index.ts
> +  | { volume: Bigish; price: Bigish | null }
We use `undefined` in other places, but maybe `null` is preferable? We should be consistent, so let's discuss and then make all of mangrove.js consistent :-)

2022-01-21 19:20 UTC, espendk commented on packages/mangrove.js/src/types/index.ts
>  export type TradeParams = { slippage?: number } & (
A bit off-topic, but I'm surprised this type lives here and not in market.ts?

2022-01-21 19:20 UTC, espendk commented on packages/mangrove.js/src/market.ts
> +        _wants = Big(params.total);
Just checked and `Big(undefined)` doesn't throw, so we should probably check that `params.total` has been set and throw otherwise.

2022-01-21 19:20 UTC, espendk commented on packages/mangrove.js/src/market.ts
> +      _wants = Big(params.wants);
`wants`  and `gives` should probably also be validated.

2022-01-21 19:20 UTC, espendk commented on packages/mangrove.js/src/market.ts
>    buy(params: TradeParams): Promise<Market.OrderResult> {
See comments for `sell`

2022-01-25 15:50 UTC, adhusson commented on packages/mangrove.js/src/types/index.ts
> +  | { volume: Bigish; price: Bigish | null }
Will leave null for now because otherwise it makes `price` optional right? And then you could easily forget to write the `price` argument and unintentionally run an order that accepts any price.

2022-01-25 15:52 UTC, adhusson commented on packages/mangrove.js/src/types/index.ts
>  export type TradeParams = { slippage?: number } & (
It seems to be used all over the place (liquidityProvider.ts, mangrove.ts, market.ts, mgvtoken.ts, offerLogic.ts, semibook.ts, index.ts)?

2022-01-25 16:16 UTC, espendk commented on packages/mangrove.js/src/types/index.ts
>  export type TradeParams = { slippage?: number } & (
When I do a whole project search on `TradeParams` I only get this result + 3 in market.ts ?

<img width="303" alt="billede" src="https://user-images.githubusercontent.com/3458856/151015374-b87daa9f-3430-42d5-8a52-0653ad05c731.png">

2022-01-25 16:23 UTC, espendk commented on packages/mangrove.js/src/types/index.ts
> +  | { volume: Bigish; price: Bigish | null }
Understood. I was thinking about this being used as a return type, but it clearly isn't.

I think we should still discuss the whole `undefined` vs `null` thing, but let's do that in the team; I'll put it on the agenda for Monday :-)

2022-01-26 15:52 UTC, adhusson commented on packages/mangrove.js/src/market.ts
> +        _wants = Big(params.total);
I'm missing something, shouldn't the typing ensure params.total has been set?

2022-01-26 15:58 UTC, espendk approved these changes

2022-01-26 16:00 UTC, adhusson commented on packages/mangrove.js/src/types/index.ts
>  export type TradeParams = { slippage?: number } & (
My bad I thought you meant Bigish! Ok moving it.

2022-01-26 16:08 UTC, espendk commented on packages/mangrove.js/src/market.ts
> +        _wants = Big(params.total);
Right, reading the type I can convince myself that that must be the case. But I'd prefer a more explicit and defensive approach - but that's just an opinion 😅

2022-01-26 16:28 UTC, merged