feat(wallet): add support for keystore file (json wallet)
mangrovedao/mangrove pull request #163
Opened 2022-01-23 01:16 UTC by akettal

2022-01-24 14:21 UTC, espendk requested changes
lgtm, just some minor comments

2022-01-24 14:21 UTC, espendk commented on packages/mangrove.js/README.md
> +    password: 'wallet_password'
Like for the `privateKey` example above, we should probably note that the password should come from the env.

2022-01-24 14:21 UTC, espendk commented on packages/mangrove.js/src/eth.ts
> +    console.log("jsonWallet options");
Should be deleted, right?

2022-01-24 19:34 UTC, akettal commented on packages/mangrove.js/README.md
> +    path: 'path/to/UTC--created_date_time--address',
Yes, that file name pattern is a practical standard (though it's not documented in an EIP), cf https://geth.ethereum.org/docs/interface/managing-your-accounts. To the point these files are sometimes called "UTC file".

2022-01-24 19:35 UTC, akettal commented on packages/mangrove.js/README.md
> +    password: 'wallet_password'
```suggestion
    password: 'wallet_password' // preferably with environment variable
```

2022-01-24 19:36 UTC, akettal commented on packages/mangrove.js/src/eth.ts
> +    console.log("jsonWallet options");
```suggestion
```

2022-01-24 19:36 UTC, akettal commented on packages/mangrove.js/src/eth.ts
> +    console.log("jsonWallet options");
Totally 😓

2022-01-25 08:07 UTC, espendk approved these changes

2022-02-22 16:07 UTC, merged