fix(mangrove.js/deps): set commonlib.js as a bundledDependency
mangrovedao/mangrove pull request #221
Opened 2022-02-28 09:13 UTC by akettal

[Bundled dependencies](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#bundleddependencies) allows to pack an internal and unpublished dependency (commonlib.js) in mangrove.js NPM package.

Fixes #220.

2022-02-28 11:00 UTC, espendk commented
I found this nice intro and guide to `bundledDependencies`: https://stackoverflow.com/a/25044361/16614325

2022-02-28 12:11 UTC, espendk requested changes
See inline comments

2022-02-28 12:11 UTC, espendk commented on .github/workflows/node.js.yml
> +    needs: [security-guard, mangrove-solidity, hardhat-utils]
As discussed we should leave the dependency in, as it is still a dependency even though the package will be bundled.

2022-02-28 13:00 UTC, akettal commented on .github/workflows/node.js.yml
> +    needs: [security-guard, mangrove-solidity, hardhat-utils]
👍

2022-02-28 20:27 UTC, espendk approved these changes
lgtm - awesomely simple solution

2022-03-01 11:51 UTC, dontrolle approved these changes

2022-03-02 12:34 UTC, closed without merging

2022-03-02 12:35 UTC, akettal commented
Closing this MR as it's not fixing the issue, see #220 for more details.