Fix: The estimateGas function triggers an error when the density is e…
mangrovedao/mangrove pull request #235
Opened 2022-03-07 18:17 UTC by johanleroch

…qual to 0 #234

2022-03-08 11:04 UTC, dontrolle requested changes
After settling the review-comments below, and the particular note that I think @adhusson or @jkrivine should just nod to the case for `density=0`, I think it's ready to go. :)

As a side-note - the `estimateGas()` func is going to be updated again when PR https://github.com/mangrovedao/mangrove/pull/231 lands. (I'll just rebase, when it's reviewed.)

2022-03-08 11:04 UTC, dontrolle commented on packages/mangrove.js/src/market.ts
> +    return estimation.gt(MAX_MARKET_ORDER_GAS) ? maxMarketOrgerGas : estimation;
Personally, I think something like the following for the last line is a bit more readable - but I'll leave this up to you.

```typescript
...
    if (estimation.lt(maxMarketOrgerGas))
      return estimation;

    return maxMarketOrgerGas;
```

2022-03-09 09:44 UTC, johanleroch commented on packages/mangrove.js/src/market.ts
> +    const maxMarketOrgerGas: BigNumber = BigNumber.from(MAX_MARKET_ORDER_GAS);
oups! thanks :)

2022-03-09 09:46 UTC, johanleroch commented on packages/mangrove.js/src/market.ts
> +    return estimation.gt(MAX_MARKET_ORDER_GAS) ? maxMarketOrgerGas : estimation;
I agree, more readable like this :)

2022-03-10 14:44 UTC, dontrolle approved these changes

2022-03-11 13:12 UTC, merged