Only one big.js import
mangrovedao/mangrove pull request #467
Opened 2022-05-13 11:21 UTC by adhusson

big.js can be configured a single time in mangrove.js.

Issue: if users import parts of mangrove.js directly (but don't import the Mangrove class), the big.js instance will not be properly configured.

2022-05-16 07:40 UTC, espendk requested changes
see comment in mangrove.ts

2022-05-16 07:40 UTC, espendk commented on packages/mangrove.js/src/mangrove.ts
>  import * as ethers from "ethers";
Maybe it would be cleaner to have initialization code in `index.ts`, i.e. the `main` file pointed to by `package.json` ?

I just tried adding a log statement to `index.ts` and then importing a sub-part of the module. The log statement was executed, so I think it's safe to assume any code in the `main` file is executed regardless of how the module is imported.

```js
// index.ts
console.log("my test");

// node REPL
> var foo = require("./dist/nodejs/mangrove.js");
my test
undefined
```

2022-05-16 07:41 UTC, espendk commented on packages/mangrove.js/src/mangrove.ts
>    Big.prototype.toString;
This should probably follow the other BIg initialization code.

2022-05-16 16:10 UTC, adhusson commented on packages/mangrove.js/src/mangrove.ts
>    Big.prototype.toString;
I don't know what you mean here?

2022-05-16 18:13 UTC, espendk commented on packages/mangrove.js/src/mangrove.ts
>  import * as ethers from "ethers";
Ok, darn - a bit weird to me, that the module system doesn't have support for module initialization. I guess we could achieve it by following a convention, e.g. all files must include a module initialization file; Would be painful to maintain though...

Regarding placement, ok. It seems weird to me to place initialization in `mangrove.ts` as it's not specific to that class, but actually initializes the whole module. If you think direct imports of sub parts is likely and something we should support, I'd argue we should go for a general solution instead of only supporting that for `mangrove.ts`.

2022-05-16 18:13 UTC, espendk reviewed
see comment

2022-05-17 16:20 UTC, adhusson commented on packages/mangrove.js/src/mangrove.ts
>  import * as ethers from "ethers";
I will keep it that way for now: it is realistic that someone would use `Mangrove` directly, but other classes are not realistic as they directly or indirectly need a Mangrove instance to be construted. So I think it hits a sweet spot in terms of being safe and not too ugly. 

Regarding generally supporting sub-parts imports, I can't think of a non-painful method yet. Also looking around module side-effects I came across this https://github.com/Microsoft/TypeScript/wiki/FAQ#why-are-imports-being-elided-in-my-emit which is... interesting.

BTW another option I tried was to have a Mangrove-only `Big` object. You would `import {Big} from "@mangrovedao/mangrove.js"` and that would be not the same class as `import Big from "big.js"`. It works, and has the advantage of not polluting the user's `Big` with our configuration... but it felt counterintuitive and more likely to lead to confusion.

2022-05-17 16:20 UTC, merged