Move from Winston to Loglevel
mangrovedao/mangrove pull request #479
Opened 2022-05-23 17:17 UTC by adhusson

Currently replaced Winston with loglevel. If fine, will 

- [ ] publish the commonlib package and 
- [ ] remove mangrove.js' logger.ts

2022-05-24 15:42 UTC, espendk requested changes
Looks good. Have added a few minor suggestions.

2022-05-24 15:42 UTC, espendk commented on packages/mangrove-solidity/config/default.js
> +      },
This seems unrelated to the rest of the PR?

2022-05-24 15:42 UTC, espendk commented on packages/commonlib.js/package.json
>    "dependencies": {
I'd expect to see `loglevel` added here as it's now a direct dependency.

2022-05-24 15:42 UTC, espendk commented on packages/commonlib.js/src/logger.ts
> +  //additionalTransports: Transport[] = []
Since we're deleting Winston, I think we should remove this - it's no longer relevant.

2022-05-24 18:28 UTC, dontrolle reviewed
Apart from the minor comments, looks good.

2022-05-24 18:28 UTC, dontrolle commented on packages/mangrove-solidity/config/default.js
> +      outputSelection: {
Apparently my comment from earlier today got deleted, so I'll repost it:
> What does this do?

2022-05-25 09:32 UTC, adhusson commented on packages/commonlib.js/src/logger.ts
> +  //additionalTransports: Transport[] = []
Do you mean removing the commented out `additionalTransports...` ?

2022-05-25 09:32 UTC, adhusson commented on packages/mangrove-solidity/config/default.js
> +      outputSelection: {
This should not be here :)

2022-05-25 13:29 UTC, espendk commented on packages/commonlib.js/src/logger.ts
> +  //additionalTransports: Transport[] = []
Yes, that's what I mean, sorry for being imprecise :-) (in my defense, GitHub is retarded - I've commented on only that line, but it's making it look like I've commented on a two-line diff 🙄)

2022-05-25 18:23 UTC, adhusson commented
I have added a fix to properly setup the loglevel, and make mangrove.js use the published version on commonlib.

I think next steps are you give a go to the bots on this branch and if everything is fine we can merge.

2022-05-30 07:25 UTC, espendk reviewed
I've renamed commonlib-js to commonlib.js.

I'll test logging in a bot and then approve.

2022-05-30 07:37 UTC, espendk approved these changes
I just checked the cleaning bot and the logs look ok.
We still need to verify once this has been deployed to Heroku.

2022-05-30 08:24 UTC, merged