Vincent
mangrovedao/mangrove pull request #56
Opened 2021-12-04 13:06 UTC by vd1

I modified the script `mangrove.js/test/scripts/printOrderBook.ts` so that one can now pass a third argument to specify the max number of offers to be displayed by the script (the default set in `market.ts` was 50)

If the user does not specify the third argument the default value is 10.

2021-12-06 10:09 UTC, espendk requested changes

2021-12-06 10:09 UTC, espendk commented on packages/mangrove.js/test/scripts/printOrderBook.ts
> +    "Usage: ts-node $0 <base token name> <quote token name> <max offers displayed>"
If the `max offers displayed` parameter is optional, it should be in square brackets:  `[max offers displayed]`

2021-12-06 10:09 UTC, espendk commented on packages/mangrove.js/test/scripts/printOrderBook.ts
> +    //demandOption: true,
This comment should probably be deleted

2021-12-06 10:09 UTC, espendk commented on packages/mangrove.js/test/scripts/printOrderBook.ts
> +    //default: 10,
Is this not working or why is it commented out? Should be deleted or commented.

I'm pretty sure yargs supports default values, so maybe should there should be a comment with a FIXME to look into that?

2021-12-06 10:09 UTC, espendk commented on packages/mangrove.js/test/scripts/printOrderBook.ts
> +//console.log(argv["_"]);
Should be deleted

2021-12-06 10:09 UTC, espendk commented on packages/mangrove.js/test/scripts/printOrderBook.ts
> +  const mangrove = await Mangrove.connect(process.env["MUMBAI_NODE_URL"]);
The script works against any Ethereum compatible network, so we should avoid using a network-specific name.
Perhaps `NODE_URL` is better?

2021-12-06 10:09 UTC, espendk commented on packages/mangrove.js/test/scripts/printOrderBook.ts
> +  // added an optional argument to define the number of offers to display
Should be deleted

2021-12-06 10:09 UTC, espendk commented on packages/mangrove.js/test/scripts/printOrderBook.ts
> +  let numberOffersDisplayed = {
Perhaps `bookOptions` is a better name here?

2021-12-07 11:33 UTC, vd1 commented on packages/mangrove.js/test/scripts/printOrderBook.ts
> +import type { BookOptions } from "../../src/types";
I deleted the second `import type BookOptions` it is not needd

2021-12-07 11:35 UTC, vd1 commented on packages/mangrove.js/test/scripts/printOrderBook.ts
> +    "Usage: ts-node $0 <base token name> <quote token name> <max offers displayed>"
done

2021-12-07 11:36 UTC, vd1 commented on packages/mangrove.js/test/scripts/printOrderBook.ts
> +  const numberOffersDisplayed = {
I am not sure - there are other options in bookOptions, eg `chunkSize`

2021-12-07 11:37 UTC, vd1 commented on packages/mangrove.js/test/scripts/printOrderBook.ts
> +    //demandOption: true,
done

2021-12-07 11:38 UTC, vd1 commented on packages/mangrove.js/test/scripts/printOrderBook.ts
> +    //default: 10,
I agree - I could not make it work, but there must be a yargs way to do it

2021-12-07 11:40 UTC, vd1 commented on packages/mangrove.js/test/scripts/printOrderBook.ts
> +    //default: 10,
i added the FIXME

2021-12-07 11:40 UTC, vd1 commented on packages/mangrove.js/test/scripts/printOrderBook.ts
> +//console.log(argv["_"]);
done

2021-12-07 11:42 UTC, vd1 commented on packages/mangrove.js/test/scripts/printOrderBook.ts
> +  const mangrove = await Mangrove.connect(process.env["MUMBAI_NODE_URL"]);
done. Notice that this works if you feed the URL on the command line; but what if you use a .env ?

2021-12-07 11:45 UTC, vd1 commented on packages/mangrove.js/test/scripts/printOrderBook.ts
> +  let numberOffersDisplayed = {
not sure - there are other options.

2021-12-07 12:51 UTC, espendk approved these changes
lgtm

2022-06-30 09:17 UTC, espendk commented
Closing this, as this `printOrderBook.ts` script is deprecated and has been superseded by the `mgv print` command: https://github.com/mangrovedao/mangrove/blob/master/packages/mangrove.js/src/cli/commands/printCmd.ts

2022-06-30 09:17 UTC, closed without merging