Feature/anviltests
mangrovedao/mangrove pull request #573
Opened 2022-08-02 19:04 UTC by adhusson

2022-08-16 06:32 UTC, espendk reviewed
I got the following errors when running the tests:

```shell
# in monorepo root
> yarn clean && yarn install && yarn build
...
> yarn test
...
➤ YN0000: Failed tests:
➤ YN0000: [FAIL. Reason: Setup failed: Invalid data] setUp() (gas: 0)
➤ YN0000: [FAIL. Reason: Setup failed: Invalid data] setUp() (gas: 0)
```

Not sure how to investigate this, so maybe a shared session would be good?

2022-08-16 06:37 UTC, espendk commented
> * scripts that update mangrove addresse in the docs after a deploy

It looks like it's not only docs, but also the mangrove.js addresses.json file that's not updated?

2022-08-16 08:52 UTC, espendk requested changes
Wheew, that's the mother of PR's 😳😅

Crazy amount of work here, kudos 👏 Looks like things will be simpler without Hardhat.

As described above, I got some errors when running the tests - maybe we should look at that together.

I only skimmed the Solidity changes - I need an intro to properly understand and, if needed, review.

Re. the things that need to be done later, I suggest we list them as tasks on the Epic to (1) ensure we remember them and (2) ease overview and delegation.

Tasks I've noted are:
- updating addresses in documentation
- CI update of addresses in mangrove.js
    - This happens as part of the build, but might be forgotten, so we should have a CI job like the old one that ensures addresses are updated.
- create repo with the deleted faucet code
- handle `files_of_unknown_use`
- FIXME in mangrove-solidity/README.md
- update documentation that references Hardhat (notion, READMEs)
- translate remaining deployment scripts
- there's a temporary synchronisation method `awaitCurrentProcessing` in Market and Semibook. Not clear to me why it's temporary? But if it is, we should log an issue on it.
- Ensure test utils aren't distributed to browsers. At the same time, it would be good to make it clear which files are test utils, eg by moving them to a separate folder.


There are more changes in this PR than removal of Hardhat, a list of these in the PR description would be good.

Things I've noted:
- yarn hoisting has been turned on
- mangrove-solidity no longer uses `node-config` for configuration
- ditto for mangrove.js. Not clear to me what replaces it?
- dotenv-flow has been removed from mangrove.js. Not clear to me what replaces it?
- contracts files have been reorganized in `mangrove-solidity`
    - extent unclear to me, maybe just `contracts/` -> `src/` ? Also maybe `contracts/test/` -> `test/`

2022-08-16 08:52 UTC, espendk commented on packages/mangrove-solidity/script/MangroveJs.s.sol
> +contract MangroveJsDeploy is MangroveDeployer {
Maybe a comment would be good here :-)

2022-08-16 08:52 UTC, espendk commented on packages/mangrove.js/config/default.js
> -  logLevel: "info",
How is log level (and other configuration) done now?

2022-08-16 08:52 UTC, espendk commented on packages/mangrove.js/src/constants.ts
>  };
I think this is equivalent to

```typescript
export const addresses = addressesPerNetwork;
```

2022-08-16 08:52 UTC, espendk commented on packages/mangrove.js/src/eth.ts
> +export class Mnemonic {
How is this related to the rest of the PR? 😅

2022-08-16 08:52 UTC, espendk commented on packages/mangrove.js/src/util/ToyENSCode.ts
> +export const address = "0xdecaf" + "0".repeat(35);
This looks like an ABI file of sorts? Maybe the file name and/or path could indicate this? And maybe a comment?

2022-08-16 08:52 UTC, espendk commented on packages/mangrove.js/src/util/getMangroveAddresses.ts
> +  [--noop] Do not actually update addresses.json.
Maybe `--dry-run` would be clearer?

2022-08-16 08:52 UTC, espendk commented on packages/mangrove.js/src/util/getMangroveAddresses.ts
> +Enumerate distributed mangrove-solidity deployments and copy required contract (one set for each chainkey) to addresses.json.
Ok, this is the replacement for the CI workflow that updated addresses.json 👍
Is this run in CI?

2022-08-16 08:52 UTC, espendk commented on packages/mangrove.js/src/util/mgvIntegrationTestUtil.ts
> +// TODO do not distribute in browser version
Maybe we could gather test utilities in a separate folder to (1) clearly signal they are for tests, and (2) easier exclusion from distribution to the browser.

2022-08-16 08:52 UTC, espendk commented on packages/mangrove.js/src/util/mgvIntegrationTestUtil.ts
> -  Taker = "taker"
I'd expect the Taker role to still be relevant in many integration tests - how come it's been removed?

2022-08-16 08:52 UTC, espendk commented on packages/mangrove.js/test/integration/simplemaker.integration.test.ts
> +        /* FIXME the effectiveGasPrice returned by anvil is incorrect, so for now we do an approx estimate. */
Could this issue be related to the tests that fail on my machine?

2022-08-16 08:55 UTC, espendk commented
Btw, my bad for all the formatting changes in the diff. When I did the Heroku build workaround I accidentally broke installation of commit hooks, so Peter's machine hasn't been running Prettier, resulting in a lot of formatting issues. It should be fixed now.

2022-08-16 10:46 UTC, adhusson commented on packages/bot-cleaning/test/mocha/config/integration-tests.json
> +    "@mangrovedao/mangrove.js/dist/nodejs/util/mochaHooks.js"
I think "mocha" gives it away? Would avoid creating a new dir -- or we can call it `testHooks`?

2022-08-16 10:48 UTC, adhusson commented on README.md
> +## Building and testing all packages
agreed, will fix.

2022-08-16 10:48 UTC, adhusson commented on packages/bot-template/test/integration/templateBot.integration.tests.ts
> +    botSigner = new ethers.Wallet(this.accounts.deployer.key);
agreed, will fix.

2022-08-16 10:50 UTC, adhusson commented on packages/bot-updategas/package.json
> +    "heroku-build-this-package": "yarn run build-this-package",
It is from b3e6e5a56d7ed8f0e28baef48a37c946434d944e do you mean things changed since this commit?

2022-08-16 11:03 UTC, adhusson commented on packages/mangrove-solidity/script/MangroveJs.s.sol
> +contract MangroveJsDeploy is MangroveDeployer {
agreed, will fix.

2022-08-16 11:04 UTC, adhusson commented on packages/mangrove-solidity/lib/forge-std-vendored/.github/workflows/tests.yml
> +name: Tests
they are :)

2022-08-16 11:07 UTC, adhusson commented on packages/mangrove.js/config/default.js
> -  logLevel: "info",
Either I removed it in error, or mangrove.js does not use it? I don't see on master where mangrove.js loads this.

2022-08-16 11:08 UTC, adhusson commented on packages/mangrove.js/src/constants.ts
>  };
technically no since after `a = {...b}`, doing b.x =2 will no change `a.x`... but I'm not sure if it matters here 😅 will fix

2022-08-16 11:11 UTC, adhusson commented on packages/mangrove.js/src/eth.ts
> +export class Mnemonic {
it is not 🫠 it's a leftover from an old way of fixing the "how to run mangrove.js tests using anvil" problem I had been trying out. will remove!

2022-08-16 11:20 UTC, adhusson commented on packages/mangrove.js/src/util/ToyENSCode.ts
> +export const address = "0xdecaf" + "0".repeat(35);
yes, well it contains an ABI (the `abi` export) and an address, and some bytecode. I'll add comments :)

2022-08-16 11:30 UTC, adhusson commented on packages/mangrove.js/src/util/getMangroveAddresses.ts
> +  [--noop] Do not actually update addresses.json.
agreed, will fix

2022-08-16 11:30 UTC, adhusson commented on packages/mangrove.js/src/util/mgvIntegrationTestUtil.ts
> +// TODO do not distribute in browser version
no, but it is run at build time!

2022-08-16 11:32 UTC, adhusson commented on packages/mangrove.js/src/util/getMangroveAddresses.ts
> +Enumerate distributed mangrove-solidity deployments and copy required contract (one set for each chainkey) to addresses.json.
no, but it is run at build time!

2022-08-16 11:33 UTC, adhusson commented on packages/mangrove.js/src/util/mgvIntegrationTestUtil.ts
> +// TODO do not distribute in browser version
makes sense, but let's table it for later?

2022-08-16 12:20 UTC, espendk commented on packages/bot-updategas/package.json
> +    "heroku-build-this-package": "yarn run build-this-package",
Sorry, my bad - I somehow thought this was in the mangrove.js package.

2022-08-16 12:22 UTC, espendk commented on packages/bot-cleaning/test/mocha/config/integration-tests.json
> +    "@mangrovedao/mangrove.js/dist/nodejs/util/mochaHooks.js"
If you know mocha is a testing library, maybe :-) Since there's also the issue of not distributing the test utilities to browsers, I think gathering those test files in a separate dir will be easiest and clearest.

2022-08-16 12:27 UTC, espendk commented on packages/mangrove.js/src/util/mgvIntegrationTestUtil.ts
> +// TODO do not distribute in browser version
Ok. It's on the list of tasks in my comment above :-)

2022-08-16 12:27 UTC, espendk commented on packages/mangrove.js/src/util/mgvIntegrationTestUtil.ts
> -  Taker = "taker"
Right. Troels and I had issues keeping track of the different roles in the integration tests, so clear and intuitive names for the roles would be good.

2022-08-18 04:14 UTC, adhusson commented on packages/bot-cleaning/test/mocha/config/integration-tests.json
> +    "@mangrovedao/mangrove.js/dist/nodejs/util/mochaHooks.js"
ok, will fix.

2022-08-18 04:15 UTC, adhusson commented on packages/mangrove.js/src/util/mgvIntegrationTestUtil.ts
> +// TODO do not distribute in browser version
I ended up doing it :)

2022-08-18 04:24 UTC, adhusson commented on packages/mangrove.js/src/util/mgvIntegrationTestUtil.ts
> -  Taker = "taker"
from [this](https://github.com/mangrovedao/mangrove/pull/573/files#diff-483a7f33e850c2c7e0280974460cb2f3434f060520a91bbc1e3576cc866be179L106) it seems that Taker was the account number 0, i.e. "deployer" now -- and I didn't see it used anywhere.

2022-08-18 04:24 UTC, adhusson commented on packages/mangrove.js/test/integration/simplemaker.integration.test.ts
> +        /* FIXME the effectiveGasPrice returned by anvil is incorrect, so for now we do an approx estimate. */
I think this should be fixed now.

2022-08-20 18:56 UTC, adhusson commented on packages/mangrove-solidity/config/custom-environment-variables.json
> -          "__name": "HARDHAT_NETWORK_CHAIN_ID",
Sorry forgot to reply, yes -- it's in the config file and/or directly from Solidity.

2022-08-20 18:57 UTC, adhusson commented on packages/mangrove.js/config/default.js
> -  logLevel: "info",
Pinging you in DM for this.

2022-08-22 07:11 UTC, espendk approved these changes
Looking good. Let's get this merged so we don't have to keep this PR up-to-date :-)

I've copied the outstanding tasks I noted earlier over to the Epic: https://github.com/mangrovedao/mangrove-tasks/issues/129
They probably need a bit of revision, but I found it better to retain them before they got lost in a merged PR.

Also, I've copied the list of additional changes I identified to the PR description. Again in the fear that they'd get lost in the comments section of a closed PR :-)
Some of these need clarification/updating, would be great if you would do that.

2022-08-22 07:11 UTC, espendk commented on packages/mangrove.js/src/cli/mgv.ts
> +  .command(nodeCmd) // note: node subcommand env vars are prefixed with MGV_NODE instead of MGV_
The command doesn't define/document any arguments/env vars?

2022-08-22 14:06 UTC, espendk commented on packages/mangrove.js/src/cli/mgv.ts
> +  .command(nodeCmd) // note: node subcommand env vars are prefixed with MGV_NODE instead of MGV_
Ah ok, I just didn't realize it as it's done in a different way than the other `mgv` commands. It's not a big deal, but I prefer that it's declared in the `*Cmd.ts` file: This way, all CLI commands and parameters are in one place, making it easy to get navigate and ensure they are consistent. The actual functionality should probably still be in another place (in the Ports-and-Adapters style).

2022-08-22 15:34 UTC, merged