feat(snipe): Add ability to snipe a list of targets
mangrovedao/mangrove pull request #605
Opened 2022-08-16 12:27 UTC by lnist

Exposes snipe on mangrove.js

2022-08-16 14:57 UTC, espendk requested changes
nice. A few minor comments, but otherwise lgtm

2022-08-16 14:57 UTC, espendk commented on packages/mangrove.js/src/market.ts
> +      offerId: ethers.BigNumberish;
It looks like we use `number` for offerIds in the code above, so should probably be the same here.

2022-08-16 14:57 UTC, espendk commented on packages/mangrove.js/src/market.ts
> +      gasLimit?: ethers.BigNumberish;
We use `number` for `gasForMarketOrder` above, so should probably be the same here.

2022-08-16 14:57 UTC, espendk commented on packages/mangrove.js/src/market.ts
> +   * `orderType`: whether to use the base/quote (buy) or quote/base (sell) market
This phrasing is weird to me - there are not two markets, only one.
Maybe we could write: "whether to snipe 'asks' or 'bids'". Maybe the parameter options should actually be "asks"/"bids"

2022-08-16 14:57 UTC, espendk commented on packages/mangrove.js/src/market.ts
> +   * `fillWants?`: fillWants specifies whether you are acting as a buyer of outbound tokens, in which case you will buy at most takerWants, or a seller of inbound tokens, in which case you will buy a
Not sure the phrasing "acting as a .." makes sense to me, so cut that out:

* `fillWants?`: specifies whether you will buy at most `takerWants` (true), or you will buy as many tokens as possible as long as you don't spend more than `takerGives` (false).

2022-08-16 14:57 UTC, espendk commented on packages/mangrove.js/src/util/trade.ts
> +   * `fillWants?`: fillWants specifies whether you are acting as a buyer of outbound tokens, in which case you will buy at most takerWants, or a seller of inbound tokens, in which case you will buy a
As above.

2022-08-16 14:57 UTC, espendk commented on packages/mangrove.js/src/util/trade.ts
> +    const fillWants = "fillWants" in params ? params.fillWants : true;
Maybe the nullish coalescing operator would be more concise:
```
const fillWants = params.fillWants ?? true
```

2022-08-16 14:57 UTC, espendk commented on packages/mangrove.js/test/integration/market.integration.test.ts
> +  it("snipe asks book for two successful orders succeeds", async function () {
I don't see `feePaid` - was it impossible to test?

2022-08-16 14:57 UTC, espendk commented on packages/mangrove.js/test/unit/semibook.unit.test.ts
> +import { Semibook, Market } from "../../";
This uses the compiled versions of Semibook and Market, right? For unit tests, maybe we should use the source code versions instead? (this would also match the following changes which do exactly that for other test files).

2022-08-17 11:03 UTC, lnist commented on packages/mangrove.js/src/market.ts
> +   * `orderType`: whether to use the base/quote (buy) or quote/base (sell) market
Agree, I've gone with both your suggestions. The asks/bids change had some additional consequences, see commit.

2022-08-17 11:04 UTC, lnist commented on packages/mangrove.js/src/market.ts
> +   * `fillWants?`: fillWants specifies whether you are acting as a buyer of outbound tokens, in which case you will buy at most takerWants, or a seller of inbound tokens, in which case you will buy a
more concise, I like it.

2022-08-17 11:05 UTC, lnist commented on packages/mangrove.js/src/util/trade.ts
> +    const fillWants = "fillWants" in params ? params.fillWants : true;
Good suggestion - It also explicitly converts null to true; and since true is meant to be the default then that is better.

2022-08-17 11:05 UTC, lnist commented on packages/mangrove.js/test/integration/market.integration.test.ts
> +  it("snipe asks book for two successful orders succeeds", async function () {
I thought it would have far-reaching consequences for tests if fees were raised. But only a few changes were needed, so I've done it :)

2022-08-17 11:06 UTC, lnist commented on packages/mangrove.js/test/unit/semibook.unit.test.ts
> +import { Semibook, Market } from "../../";
We flipped back and forth locally trying to fix build errors. I still think vscode gets confused sometimes (in integration tests) and I am not entirely sure what happens. But here I agree it should point to src.

2022-08-17 13:11 UTC, espendk approved these changes
lgtm

The new non-zero fee in integration tests should probably be announced to the dev team so people are aware of it.

2022-08-17 13:11 UTC, merged