Feature/marketclean
mangrovedao/mangrove pull request #629
Opened 2022-08-19 09:03 UTC by lnist

2022-08-19 09:21 UTC, espendk reviewed
nice improvement :-) One question though re. disonnecting a semibook, see below.

2022-08-19 09:21 UTC, espendk commented on packages/mangrove.js/test/integration/semibook.integration.test.ts
> +      market.getSemibook("asks").disconnect();
How come the semibook should be disconnected? I think this breaks the idea of the test as we're no longer observing how the semibook responds to events (it doesn't receive any?)

2022-08-19 12:51 UTC, lnist commented
@espendk : Do you have an opinion on the parseLogs question above? and does the other answer resolve the conversation?

2022-08-19 13:59 UTC, espendk commented
> @espendk : Do you have an opinion on the parseLogs question above? and does the other answer resolve the conversation?

I don't see any questions on this page at all, except the one I asked re. disconnecting the semibook?

2022-08-22 06:29 UTC, espendk requested changes

2022-08-22 06:29 UTC, espendk commented on packages/mangrove.js/test/integration/semibook.integration.test.ts
> +      market.getSemibook("asks").disconnect();
There's a synchronization barrier before checking the cache, so there shouldn't be a race condition.
So I see three possibilities:
1. the synchronization barrier isn't working as it should
2. the test is wrong, ie `getBestInCache` should not return `undefined` after an offer has been added. Note though that the cache is partial and events don't carry sufficient information to always keep the cache full, so it's not obvious to me that the new offer should be in the cache
3. there's a bug

I don't know what the answer is, that requires some investigation. But I'm quite sure that disconnecting the semibook makes the test pointless.

2022-08-22 06:29 UTC, espendk commented on packages/mangrove.js/src/util/trade.ts
> +          events.filter((x) => x.address === market.mgv._address);
I don't think there's any other way to do it. I think the reason is that the contract object you're using to send the tx only knows the ABI of the cleaner contract and thus it can only parse events from that, so it only populates `events` with cleaner contract events. 

But @adhusson would know better :-)

2022-08-22 09:47 UTC, lnist commented on packages/mangrove.js/test/integration/semibook.integration.test.ts
> +      market.getSemibook("asks").disconnect();
I've changed it to use the new sync mechanism instead and asserting that the book _does_ get updated in the test.

2022-08-22 11:57 UTC, merged