Deploy reads addresses
mangrovedao/mangrove pull request #719
Opened 2022-09-16 12:22 UTC by adhusson

* Scripts read address files so known deployed addresses are accessible and don't need to be reflected everywhere in the commandline.

* There is a Mumbai Fork contract

* Scripts can also access known Fork addresses from the corresponding Fork contract (PolygonFork, MumbaiFork)

* Scripts can specify `--etherscan-api-key mumbai` and `foundry.toml` will figure things out from your .env

* Some small reorg/renamings

2022-09-19 07:54 UTC, lnist reviewed
partial review :)

2022-09-19 07:54 UTC, lnist commented on packages/mangrove-solidity/script/ActivateMangroveOrder.s.sol
> +    mgvOrder: address of MangroveOrder(Enriched) contract
consider using natspec so that it becomes a habit (just in future commits, not important enough to change this one)

2022-09-19 07:54 UTC, lnist commented on packages/mangrove-solidity/script/ActivateMangroveOrder.s.sol
> +    mgvOrder: address of MangroveOrder(Enriched) contract
I see, these are actually not for a function signature, but env variables - however, the env variables are named TKNS.
Maybe let the contract doc only describe the env variables and then let the inner_doc describe the variables (if needed)? (same goes for other contracts)

2022-09-19 07:54 UTC, lnist commented on packages/mangrove-solidity/script/ActivateMangroveOrder.s.sol
> +    inner_run({
innerRun instead of inner_run?

2022-09-20 17:35 UTC, adhusson commented on packages/mangrove-solidity/script/ActivateMangroveOrder.s.sol
> +    mgvOrder: address of MangroveOrder(Enriched) contract
will add natspeccing as a todo, currently readable enough. Also natspec to me is mostly useful because Etherscan uses it to document its read/write contract tabs, but scripts will never end up on etherscan. WDYT?

2022-09-21 06:52 UTC, lnist commented on packages/mangrove-solidity/script/ActivateMangroveOrder.s.sol
> +    mgvOrder: address of MangroveOrder(Enriched) contract
fine by me - was mostly to get muscle memory :D

2022-09-21 07:28 UTC, lnist requested changes
Some minor fixes suggested

2022-09-21 07:28 UTC, lnist commented on packages/mangrove-solidity/script/lib/Deployer.sol
> +   2. In a toy ENS instance. Useful for testing when the server & testingbi script
bi?  looks like a vi command :D

2022-09-21 07:47 UTC, adhusson commented on packages/mangrove-solidity/addresses/context/polygon.json
> +    "isToken": false,
I will remove it, it is used for MangroveJsDeploy so that mangrove.js knows when to ask for the contract's decimals. I'm working on another way for mangrove.js to get that info so JSON files don't get polluted by this.

2022-09-21 07:47 UTC, adhusson commented on packages/mangrove-solidity/script/Ba.s.sol
> +// SPDX-License-Identifier:	AGPL-3.0
It should not be there :)

2022-09-21 07:49 UTC, adhusson commented on packages/mangrove-solidity/script/lib/Deployer.sol
> +   2. In a toy ENS instance. Useful for testing when the server & testingbi script
it is 😅

2022-09-21 09:08 UTC, adhusson commented on packages/mangrove-solidity/script/ConfigureMgvOracle.s.sol
> +    try vm.envAddress("GASBOT") returns (address gasbot) {
will discuss in DM :)

2022-09-21 09:10 UTC, lnist approved these changes

2022-09-21 09:10 UTC, merged